### PR TITLE
CI via Github Actions

### PR DESCRIPTION
**Pull request by weijiekoh**
This PR implements CI via Github Actions. It just runs `./e2e_blobstream_inclusion.sh` on the existing example proofs in the repo.

### CODE REVIEW

**Comment by kobigurk** [comment]
Thanks! Can you also run the risc zero example?

**Comment by weijiekoh** [comment]
@kobigurk CI passes, including the risc0 example, but takes 5h 17m.

**Comment by kobigurk** [comment]
Tough, but still worth it I think

Wdyt?

**Comment by weijiekoh** [comment]
Imo, no harm merging unless it impacts the organisation's Github Actions quotas!

**Pull request merged**
